nameOverride: ""
fullnameOverride: ""

image:
  repository: vbabichev/metrics-app
  pullPolicy: IfNotPresent
  tag: latest

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hosts:
    - host: metrics-app.local
      paths: []

resources: {}
tolerations: []
affinity: {}

metrics:
  port: http
  prometheusRules: {}
  scanInterval: 30s
  serviceMonitor: false
