{{- if .Values.metrics.prometheusRules }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "metrics-app.fullname" . }}
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
spec:
  groups:
  - name: {{ include "metrics-app.fullname" . }}
    rules:
    {{- toYaml .Values.metrics.prometheusRules | nindent 4 }}
{{- end }}
