nameOverride: ""
fullnameOverride: ""

image:
  repository: cloudprober/cloudprober
  pullPolicy: IfNotPresent
  tag: latest

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hosts:
    - host: cloudprober.local
      paths: ["/"]

resources: {}
tolerations: []
affinity: {}

metrics:
  port: web
  prometheusRules: {}
  scanInterval: 30s
  serviceMonitor: false
